-- Vocab
ALTER TABLE vocabulary_topic ALTER COLUMN id TYPE VARCHAR(100);

ALTER TABLE vocabulary ALTER COLUMN id TYPE VARCHAR(100);
ALTER TABLE vocabulary ALTER COLUMN topic_id TYPE VARCHAR(100);

ALTER TABLE vocabulary_test ALTER COLUMN id TYPE VARCHAR(100);
ALTER TABLE vocabulary_test ALTER COLUMN topic_id TYPE VARCHAR(100);

ALTER TABLE vocabulary_test_question ALTER COLUMN id TYPE VARCHAR(100);
ALTER TABLE vocabulary_test_question ALTER COLUMN test_id TYPE VARCHAR(100);

-- Grammar
ALTER TABLE grammar_topic ALTER COLUMN id TYPE VARCHAR(100);

ALTER TABLE grammar ALTER COLUMN id TYPE VARCHAR(100);
ALTER TABLE grammar ALTER COLUMN topic_id TYPE VARCHAR(100);

ALTER TABLE grammar_test ALTER COLUMN id TYPE VARCHAR(100);
ALTER TABLE grammar_test ALTER COLUMN grammar_id TYPE VARCHAR(100);

ALTER TABLE grammar_test_question ALTER COLUMN id TYPE VARCHAR(100);
ALTER TABLE grammar_test_question ALTER COLUMN test_id TYPE VARCHAR(100);

-- Listening
ALTER TABLE listening_topic ALTER COLUMN id TYPE VARCHAR(100);

ALTER TABLE listening ALTER COLUMN id TYPE VARCHAR(100);
ALTER TABLE listening ALTER COLUMN topic_id TYPE VARCHAR(100);

ALTER TABLE listening_test ALTER COLUMN id TYPE VARCHAR(100);
ALTER TABLE listening_test ALTER COLUMN topic_id TYPE VARCHAR(100);

ALTER TABLE listening_test_question ALTER COLUMN id TYPE VARCHAR(100);
ALTER TABLE listening_test_question ALTER COLUMN test_id TYPE VARCHAR(100);

-- Toeic--
ALTER TABLE toeic_test_group
ALTER COLUMN id TYPE VARCHAR(100);

ALTER TABLE toeic_test
ALTER COLUMN id TYPE VARCHAR(100),
    ALTER COLUMN group_id TYPE VARCHAR(100);

ALTER TABLE toeic_test_question_group
ALTER COLUMN id TYPE VARCHAR(100),
    ALTER COLUMN test_id TYPE VARCHAR(100);

ALTER TABLE toeic_test_question
ALTER COLUMN id TYPE VARCHAR(100),
    ALTER COLUMN question_group_id TYPE VARCHAR(100);

---
ALTER TABLE topic_view_statistic
ALTER COLUMN id TYPE VARCHAR(100),
    ALTER COLUMN topic_id TYPE VARCHAR(100);