spring:
  flyway:
      enabled: true
      locations: classpath:db/migration
  application:
    name: user-service
  datasource:
    url: ${DB_CONNECTION_URL:jdbc:postgresql://localhost:5432/userservice}
    username: ${DB_CONNECTION_USERNAME:dbowner}
    password: ${DB_CONNECTION_PASSWORD:dbowner}
  mail:
    username: ${MAIL_USERNAME:your_email}
    password: ${MAIL_PASSWORD:your_password}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      connect-timeout: 200ms # Thời gian tối đa để kết nối
      timeout: 500ms         # Thời gian tối đa đợi phản hồi
      lettuce:
        pool:
          max-active: 8      # Số lượng kết nối tối đa trong pool
          max-idle: 8
          min-idle: 0
      repositories:
        enabled: false
    cache:
      type: redis              # Khai báo sử dụng Redis cho @Cacheable
server:
    port: 8081
    servlet:
        context-path: /user-service
jwt:
    signerKey: ${SIGNER_KEY:t47lu0FHQY5XHLeC5uViwOtAuzBT0cpkFdDgWZfrRHF1Y2e6XB2oVVRHzKyb/9Fa}
    refreshable-duration: 2764800 # in second
    valid-duration: 2764800 # in second

springdoc:
  override-with-generic-response: false

cloudinary:
  cloud_name: ${CLOUD_NAME:your_cloud_name}
  api_key: ${CLOUD_API_KEY:your_cloud_key}
  api_secret: ${CLOUD_API_SECRET:your_cloud_secret_key}