ALTER TABLE exam_history
ALTER COLUMN id TYPE VARCHAR(100),
    ALTER COLUMN test_id TYPE VARCHAR(100);

ALTER TABLE user_answer_group
ALTER COLUMN id TYPE VARCHAR(100),
    ALTER COLUMN exam_history_id TYPE VARCHAR(100);

ALTER TABLE user_answer
ALTER COLUMN id TYPE VARCHAR(100),
    ALTER COLUMN user_answer_group_id TYPE VARCHAR(100);

ALTER TABLE favorite
ALTER COLUMN id TYPE VARCHAR(100),
    ALTER COLUMN item_id TYPE VARCHAR(100);

ALTER TABLE plan ALTER COLUMN id TYPE VARCHAR(100);

ALTER TABLE plan_group
ALTER COLUMN id TYPE VARCHAR(100),
    ALTER COLUMN plan_id TYPE VARCHAR(100);

ALTER TABLE plan_detail
ALTER COLUMN id TYPE VARCHAR(100),
    ALTER COLUMN plan_group_id TYPE VARCHAR(100),
    ALTER COLUMN topic_id TYPE VARCHAR(100);

ALTER TABLE comment
ALTER COLUMN id TYPE VARCHAR(100),
    ALTER COLUMN test_id TYPE VARCHAR(100),
    ALTER COLUMN parent_id TYPE VARCHAR(100),
    ALTER COLUMN reply_id TYPE VARCHAR(100);