spring:
  application:
    name: content-service
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: ${DB_CONNECTION_URL:jdbc:postgresql://localhost:5433/contentservice}
    username: ${DB_CONNECTION_USERNAME:dbowner}
    password: ${DB_CONNECTION_PASSWORD:dbowner}

server:
  port: 8082
  servlet:
    context-path: /content-service

cloudinary:
  cloud_name: ${CLOUD_NAME:your_cloud_name}
  api_key: ${CLOUD_API_KEY:add_your_key}
  api_secret: ${CLOUD_API_SECRET:add_your_key}

app:
  services:
    agent: ${AGENT_SERVICE_URL:http://localhost:5000/agent-service}